books = [
    {
        "id": 1,
        "title": "The Hobbit",
        "author": "JRR Tolkien",
        "publisher": "Harper Collins",
        "published_date": "2006-10-01",
        "page_count": 389,
        "language": "English",
    },
    {
        "id": 2,
        "title": "The Lord of the Rings - The Fellowship of the Ring",
        "author": "JRR Tolkien",
        "publisher": "Harper Collins",
        "published_date": "2006-10-01",
        "page_count": 389,
        "language": "English",
    },
    {
        "id": 3,
        "title": "The Silmarillion",
        "author": "JRR Tolkien",
        "publisher": "Harper Collins",
        "published_date": "2006-10-01",
        "page_count": 389,
        "language": "English",
    },
    {
        "id": 4,
        "title": "The Lord of the Rings - The Two Towers",
        "author": "JRR Tolkien",
        "publisher": "Harper Collins",
        "published_date": "2006-10-01",
        "page_count": 389,
        "language": "English",
    },
    {
        "id": 4,
        "title": "The Lord of the Rings - The Return of the King",
        "author": "JRR Tolkien",
        "publisher": "Harper Collins",
        "published_date": "2006-10-01",
        "page_count": 389,
        "language": "English",
    },
]
